### ISSUE TITLE
Generator non linearity missing?

### ISSUE THREAD

**Issue by dmarnerides** [martinarjovsky/WassersteinGAN#29]
Hey,

I noticed that the dcgan generator ends with a Tanh non-linearity whereas the mlp has no non-linearity at the end. Is this done on purpose? Am I missing something?

**Comment by martinarjovsky** [comment]
Hi! We just found this a few days ago. We double checked with the code we used for the paper and it's exactly the same (we forgot to add the tanh in there as well).

Strictly speaking the tanh unit is not necessary, since the MLP can (and should) learn by itself to produce pixels between -1 and 1. You can add the tanh if you want, I don't think it will make a difference (some students from the Montréal lab also ran the same experiment with tanh and got the same thing).
