### ISSUE TITLE
ask for code

### ISSUE THREAD

**Issue by ChampionZP** [martinarjovsky/WassersteinGAN#30]
i have been studying your paper：《Wasserstein GAN》， could you share the code corresponding to figure 2, page 9 in your paper to me ? 
 thanks very much! And WGAN is a masterpiece in my mind !!

**Comment by martinarjovsky** [comment]
Hi! I was looking around but I couldn't find the exact code. I think @soumith may have it somewhere. 

The code was a modification of this one with 1D gaussians instead of 2D, hope it helps :). I haven't run this code in centuries so you may have to play with it a bit but it's all in there.

https://gist.github.com/martinarjovsky/eaf675b622e512ba1b554f16a877b49b

Thanks for the nice comments!
